### ISSUE TITLE
Update Dockerfile to incorporate latest version of docker-compose

### ISSUE THREAD

**Issue by brandshaide** [jonaskello/docker-and-compose#2]
Hi and thank's for your nice work! 

I'd be awesome if you could update your Dockerfile to incorporate the latest version of docker-compose (which is - as of 01-2018 - [1.18.0](https://github.com/docker/compose/releases/tag/1.18.0)) 

Background: I'd like to utilize docker-compose in my GitLab CI pipeline and using the  feature `--exit-code-from some-service`  - which is not available in the version of `docker-compose` you are utilizing in the `Dockerfile` ( `1.11.2`). 

Thanks in advance. 

Best
Philipp

**Comment by jonaskello** [comment]
Sure, do you want to make a PR for that?

**Comment by brandshaide** [comment]
> Sure, do you want to make a PR for that?

done.

**Comment by jonaskello** [comment]
I made a separate branch for it so it should be available as tag `17.03.0-1.18.0` once docker hub has built it.
