### ISSUE TITLE
Is an environment variable missing or what else?

### ISSUE THREAD

**Issue by jurgenhaas** [jonaskello/docker-and-compose#4]
I'm running this on a self-hosted GitLab instance which runs the latest release and my runner configuration looks like this:

```
[[runners]]
  name = "Drupal Deploy Test"
  url = "https://gitlab.example.com/"
  token = "4c5e755047ce0e98ee5f91d962ebd9"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "jonaskello/docker-and-compose:17.03.0-1.18.0"
    privileged = true
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
```

When running docker or docker-compose inside the container I'm getting an error like

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Looks like the DOCKER_HOST environment variable isn't set and if I do `export DOCKER_HOST="tcp://172.17.0.10:2375"` I can then run docker and docker-compose.

However, that leads to another error when running docker-compose:

```
ERROR: for php  Cannot create container for service php: create .: volume name is too short, names should be at least two alphanumeric characters
```

That's confusing because the same docker-compose file works locally and even if I replaced the volume definition `./:/var/www/html` with the fully qualified path, the error remains the same.

Any idea what I could be doing?

**Comment by aroldoxleite** [comment]
change the config.toml file to

`volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]`

**Comment by jurgenhaas** [comment]
This is spot on, thanks @aroldoxleite for your advise. It is working just fine.

Now, when I'm using docker-compose inside the container and need to use volumes it seems that those are not working. Any advise on how I could approach that scenario?

**Comment by jurgenhaas** [comment]
So what I found is that starting a container from within a container does work but mounting volumes is tricky such that the volume source is not the full path from within the current container but from the host as well. That means I have to find out the correct path which needs to be mounted and then everything is working just fine.
