### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by mikos** [jonaskello/docker-and-compose#9]
Since updating to `19.03.12-1.26.2` my GitLab deployment pipeline started to fail with the following error:-

```
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted (core dumped)
```

I rolled back to `17.03.0-1.18.0` and everything was fine again. It looks like docker-compose requires libgcc as a dependency as of 1.20 (see https://github.com/docker/compose/pull/5817)

**Comment by crazymerg** [comment]
Looks like my fail. I tested just like this...
> ~/d/docker-and-compose (master|✔) $ docker run -ti docker-compose sh                                                                                                                                
/ # docker-compose -v
docker-compose version 1.26.2, build eefe0d31

Sorry, will try to fix it faster.

ps: my own pipeline failed after i switched version today xD

**Comment by crazymerg** [comment]
https://github.com/jonaskello/docker-and-compose/pull/10
this fixes my pipeline
